[project]
name = "cherubini"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "pigpio",
    "paho-mqtt",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
